### PR TITLE
add a method to retrieve page's data

### PR DESCRIPTION
**Pull request by rakk7**
closes: https://github.com/inertiajs/inertia-laravel/issues/7

### CODE REVIEW

**Comment by reinink** [comment]
So I like the idea here, and the use-cases you outline in #7 are good ones. That said, I'm not sure this implementation makes sense.

Does it really make sense to send data that may only be used in the server-side rendering with every Inertia request? This just bloats the JSON response unnecessarily.

It makes me wonder if we should consider something like this:

```php
class EventsController extends Controller
{
    public function show(Event $event)
    {
        return Inertia::render('Event', [
            // Only for JavaScript rendering
            'event' => $event->only('id', 'title', 'start_date', 'description'),
        ], [
            // Only for sever side rendering
            'meta_description' => $event->meta_description,
            'twitter_card' => 'summary_large_image',
            'twitter_image' => $event->twitter_image,
        ]);
    }
}
```

Admittedly, quite often there could be overlap between the two, for example, the title. Need to think on this a little.

**Comment by rakk7** [comment]
I agree with you, I think we can add an optional method ```->with($data)``` for the data that will be only used for server-side. ( this can be a in separate issue topic )

```
return View::make($this->rootView, [
    'page' => [
        'component' => $component,
        'props' => array_merge($this->sharedProps, $props),
    ],
])->with($this->viewData);
```
---
On the other hand, we still need a way to access the same page's data in blade, such as the "title" case. In which this PR trying to do.

**Comment by reinink** [comment]
Wait a minute, this already works:

```php
return Inertia::render('Event', ['event' => $event])
                ->with(['meta_description' => 'something']);
```

Which means you can get access to this data in your root template:

```blade
{{ $meta_description }}
```

That's because `Inertia::render()` returns a `View` instance. Which means, you can also get access to the props data this way:

```blade
{{ $page['props']['event']->title }}
```

We could still add `Inertia::get()` to make accessing the prop data easier, but really, this is more of a documentation issue.

I'm going to test this PR and see how it feels.

**Comment by rakk7** [comment]
Just wow, how did i missed that! 💯IQ 😞

**Comment by reinink** [comment]
Hah, it wasn't immediately obvious to me either. I'm going to add this to the docs.

**Comment by reinink** [comment]
Merged, and added to docs: 0f7bbcc712eb58f0ddc8f8d64f9474f79809cdec

**Pull request merged**
