### PR TITLE
Fix casing of X-Inertia-Error-Bag HTTP header

### PR DESCRIPTION
**Pull request by szepeviktor**
As per https://github.com/inertiajs/inertia/blob/896c53bb0e80bb6ba56e588a3afe665fa8aa0498/packages/inertia/src/inertia.js#L231

### CODE REVIEW

**Comment by reinink** [comment]
Did you actually run into a bug with this? The reason we're using lowercase headers in PHP (Laravel) is because the `Symfony\Component\HttpFoundation\HeaderBag` automatically lowercases them.

```php
dd($request->headers);
```

image

**Comment by szepeviktor** [comment]
> `Symfony\Component\HttpFoundation\HeaderBag` automatically lowercases them.

Isn't HTTP/2 _who_ lowercases them??

**Comment by szepeviktor** [comment]
No!

https://github.com/symfony/http-foundation/blob/5.x/HeaderBag.php#L131

Symfony does it.

May I lowercase all other header names?

X-Inertia
X-Inertia-Version
X-Inertia-Partial-Data
X-Inertia-Partial-Component

**Comment by szepeviktor** [comment]
@reinink What do you think?

**Comment by reinink** [comment]
> May I lowercase all other header names?

I'm not sure what you mean. These headers are set by Inertia, and then server-side in PHP they are lowercased. This all just works right now, so I'm not really sure what you're asking.

I'd suggest we just leave things as they are, unless there's a bug.

**Comment by szepeviktor** [comment]
> I'd suggest we just leave things as they are, unless there's a bug.

When I've received the header list from a developer using Inertia I've noticed one of them is all lowercase.

@reinink Could you we make all of them the same case?

**Pull request closed without merging**
