### PR TITLE
Check middleware Response instance before trying to modify for Inertia

### LINKED ISSUE #400: Undefined method Symfony\Component\HttpFoundation\StreamedResponse::header()
Hi,

In one of my projects I'm making use of a streamed response, so `return response()->stream()`. Since the upgrade to 0.6.1 I'm seeing the following error:

`Error: Call to undefined method Symfony\Component\HttpFoundation\StreamedResponse::header() in file /var/www/<projectname>/vendor/inertiajs/inertia-laravel/src/Middleware.php on line 90
`

Probably related to changes made in #398?

### LINKED ISSUE #401: Call to undefined method Symfony\Component\HttpFoundation\BinaryFileResponse::header()
When I upgraded my application to the latest and greatest (php8.1, latest Laravel) I encountered this error:

```
 Error: Call to undefined method Symfony\Component\HttpFoundation\BinaryFileResponse::header() in .../vendor/inertiajs/inertia-laravel/src/Middleware.php:90
```

Looks like it can be fixed by changing line 90 in `src/Middleware.php`
``` 
$response->header('Vary', 'Accept');
```
 to 
```
$response->headers->set('Vary', 'Accept');
```
according to https://laracasts.com/discuss/channels/laravel/call-to-undefined-method-binaryfileresponseheader-1

### PR DESCRIPTION
**Pull request by crynobone**
* fixes #400 
* fixes #401

### CODE REVIEW

**Comment by crynobone** [comment]
Alternatively we could just set the header from Response https://github.com/inertiajs/inertia-laravel/blob/a232be0c66de6552314e32effaf78b3dd16a20b0/src/Response.php#L110

**Comment by reinink** [comment]
> Alternatively we could just set the header from Response

I tried this originally, but if there is a redirect between two Inertia endpoints, even that redirect response needs the `Vary` header set, otherwise it doesn't work — at least from my testing in Safari, where this issue exists.

**Comment by crynobone** [comment]
> I tried this originally, but if there is a redirect between two Inertia endpoints, even that redirect response needs the Vary header set, otherwise it doesn't work — at least from my testing in Safari, where this issue exists.

Check the code to explicitly check for `Illuminate\Http\Response`, `Illuminate\Http\JsonResponse` or `Illuminate\Http\RedirectResponse`. This should cover most of the use-case and allows `Accept: Vary` to be skipped from any custom Symfony based Response.

**Comment by reinink** [comment]
@crynobone Can you think of any practical reason why including `Accept: Vary` on those other responses is bad? Because as far as I can tell it just tells the browser to be more careful about how it caches the response.

**Comment by reinink** [comment]
> I don't necessarily feel that it's bad. Just that it changes the header on responses unrelated to Inertia scope (initial HTML page, redirects, and JSON responses). If those response needs to have the header it should be explicitly defined by the related code.

Yeah, I don't disagree, but again, from my testing, it doesn't work unless it's on at least all Inertia endpoints (HTML and JSON), *plus* any 301 redirects that end up on an Inertia endpoint.

Further, I'm starting to think that `Vary: Accept` is actually the wrong header to begin with. Like, it's been working to this point, but I think mostly by chance. I think the header we should be using is `Vary: X-Inertia`.

I'm working on a PR that implements all of that — which I think is the better fix this what's in this PR.

**Pull request closed without merging**
