### PR TITLE
Merge inertia-laravel-testing into inertia-laravel

### PR DESCRIPTION
**Pull request by claudiodekker**
# Testing
After multiple months of beta testing, this PR makes [the inertia-laravel-testing library](https://github.com/claudiodekker/inertia-laravel-testing) an official part of the inertia-laravel adapter 🎉 

While the inertia-laravel-testing library WILL remain available for installation, but WILL NOT receive any further (security) updates going forward.

# Migrating

To migrate from `inertia-laravel-testing` to the `inertia-laravel` adapter, simply follow these easy steps:
1. In your `composer.json` file, remove the `claudiodekker/inertia-laravel-testing` dependency line
2. In your `composer.json` file, change the version of `inertiajs/inertia-laravel` to `^0.4.0`
3. Run `composer update`
4. Search and replace `use ClaudioDekker\Inertia\Assert;` with `use Inertia\Testing\Assert;` in your test suites.

That's it! When done correctly, all of your tests should still be passing.

### CODE REVIEW

**Comment by eballeste** [comment]
@claudiodekker hi! thanks for this! how do you use this?

I looked at the tests directory and tried to recreate something very simple but keep getting:
`Undefined type 'Inertia\Testing\Assert'`

```php
namespace Tests\Feature\Frontend\Pages;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Inertia\Testing\Assert;
use Tests\TestCase;

class HomePageTest extends TestCase
{
    use RefreshDatabase;

    /** @test */
    function i_can_see_the_homepage()
    {
        $response = $this->get(route('home'));

        $response->assertInertia(fn (Assert $inertia) => $inertia
            ->component('Home')
        );
    }
}
```

**Comment by eballeste** [comment]
ouuu I didn't notice that this had just been merged! talk about timing!

i upgraded this package via composer and my test passed

**Comment by claudiodekker** [comment]
> @claudiodekker hi! thanks for this! how do you use this?
> 
> I looked at the tests directory and tried to recreate something very simple but keep getting:
> `Undefined type 'Inertia\Testing\Assert'`
> 
> ```
> namespace Tests\Feature\Frontend\Pages;
> 
> use Illuminate\Foundation\Testing\RefreshDatabase;
> use Inertia\Testing\Assert;
> use Tests\TestCase;
> 
> class HomePageTest extends TestCase
> {
>     use RefreshDatabase;
> 
>     /** @test */
>     function i_can_see_the_homepage()
>     {
>         $response = $this->get(route('home'));
> 
>         $response->assertInertia(fn (Assert $inertia) => $inertia
>             ->component('Home')
>         );
>     }
> }
> ```

Right now, we don't have documentation for this _on our website_ yet, but since this is pretty much entirely the 'old' testing helpers library, [you can find the documentation here](https://github.com/claudiodekker/inertia-laravel-testing/blob/8c8191b2b910ebdd4979911c9fbae60a188a85b4/README.md)

**Comment by j-dexx** [comment]
Can we port the testing documentation somewhere more noticeable?

Being laravel specific doesn't make sense on the main inertia docs to me personally but in the readme maybe or wiki (which seems to exist but if I click github just redirects back to the main page)?

**Comment by sebastiaanluca** [comment]
The documentation for this seems to be quite hidden 😅  Found some under https://inertiajs.com/releases/inertia-laravel-0.4.0-2021-03-02#top that redirected me to https://github.com/claudiodekker/inertia-laravel-testing/tree/a5ac8d372e456534f5ad2e07a6875e0f27c6a73d.

**Comment by reinink** [comment]
@sebastiaanluca Yeah, this really needs more attention. I just haven't had the time to get this done yet.

To help things a little, I've just added a new "Testing" page to the website (https://inertiajs.com/testing), which outlines some testing basis, and mentions the Laravel testing helper.

**Comment by reinink** [comment]
@sagalbot Heh, no, I haven't had a chance to think that through yet. It's kind of tricky, as it requires a ton of documentation. It would looks something like the new [Fluent JSON Testing](https://laravel.com/docs/8.x/http-tests#fluent-json-testing) Laravel docs and the [existing docs that Claudio wrote](https://github.com/claudiodekker/inertia-laravel-testing/tree/a5ac8d372e456534f5ad2e07a6875e0f27c6a73d) for this.

If you're still up to taking a crack at this, I'd be happy to give you access to the website repo. Let me know. 👍

**Pull request merged**
