### PR TITLE
Allow URL override for response

### PR DESCRIPTION
**Pull request by FrittenKeeZ**
Umbrella change for:
- #236
- #359
- #360
- #421
- #422
- #437
- #446

### CODE REVIEW

**Comment by rojtjo** [comment]
The thing I dislike about this is that you'd be required to manually call the `toResponse` method from your controller or middleware.

I would probably prefer a solution where you'd be able to just override a method on the `HandleInertiaRequests` middleware to define a resolver. This way there is no need to manually call the `toResponse` method and the framework can just handle the rest.

```php
use Inertia\Middleware;

class HandleInertiaRequests extends Middleware
{
    public function urlResolver(Request $request): ?callable
    {
        return fn (Request $request) => 'https://inertiajs.com/'.$request->getRequestUri();
    }
}
```

I've prepared possible solution for this here: https://github.com/inertiajs/inertia-laravel/compare/master...rojtjo:inertia-laravel:feature/url-override

**Comment by FrittenKeeZ** [comment]
@rojtjo I like that method a lot - I initially thought about making a resolver on the response class itself, but it would basically be the same thing, as you had to call `toResponse` as well.

**Comment by FrittenKeeZ** [comment]
@rojtjo would you consider making a PR with your changes?

**Comment by rojtjo** [comment]
Sure, no problem!

**Comment by FrittenKeeZ** [comment]
Closing this in favor of #503 which works as expected

**Pull request closed without merging**
